services:
  - type: web
    name: crm
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y unixodbc-dev
      pip install -r requirements.txt
    startCommand: streamlit run crm.py --server.port $PORT
